ITL-4 Implement base state of todo card
BiroAron/ToDo pull request #5
Opened 2023-08-02 06:51 UTC by BiroAron

2023-08-04 06:11 UTC, kincsokiss requested changes

2023-08-04 06:11 UTC, kincsokiss commented on src/components/todo/ToDoDeleteButton.vue
> +    class="bg-gray-300 py-2 px-7 rounded-xl font-semibold text-black flex justify-center align-center"
Please create a general Button.vue component, enable to set the classes, button title and the function for click event as props. Use this component as Delete and Save buttons insetad of TodoDeleteButton and TodoSaveButton components. Those Vue components are almost the same.

2023-08-04 11:56 UTC, kincsokiss requested changes

2023-08-04 11:56 UTC, kincsokiss commented on src/components/todo/Button.vue
> +  if (props.buttonName === 'Save') emit('handleSaveClick')
What will happen if there will be further buttons? Ex. update, delete etc. ? Will you add them to this if..else statement and to the emits as well? 
I general button has not to know about what kind of button is. It receive all of the specific details as props and emits. It has a click event which has to emit a function, but the parent component has to handle this.

2023-08-04 14:27 UTC, gerebdavid commented on src/components/todo/ToDoDescription.vue
> +    @input="handleInput"
move events after attributes

2023-08-04 14:31 UTC, gerebdavid commented on src/components/todo/ToDoDescription.vue
> +    :value="description"
Use v-model instead of :value and create a computed with getter setter

2023-08-04 14:32 UTC, gerebdavid commented on src/components/todo/ToDoForm.vue
> +          :buttonstyles="'bg-primary text-white'"
You dont have to add : to buttonstyles prop cause the value is a string

2023-08-04 14:32 UTC, gerebdavid commented on src/components/todo/ToDoForm.vue
> +          :button-name="'Save'"
same on button-name

2023-08-04 14:34 UTC, gerebdavid commented on src/components/todo/ToDoPriority.vue
> +        <li>
Use v-for on <li> instead of creating three li element

2023-08-04 14:34 UTC, gerebdavid commented on src/components/todo/ToDoPriority.vue
> +    <div
Same here

2023-08-04 14:35 UTC, gerebdavid commented on src/components/todo/ToDoPriority.vue
> +  else return 'border-none'
If you return inside if you dont have to use else

2023-08-04 14:35 UTC, gerebdavid commented on src/components/todo/ToDoTitle.vue
> +    :value="title"
Do the same like in TodoDescription

2023-08-07 10:22 UTC, gerebdavid approved these changes

2023-08-07 11:09 UTC, merged