ITL-6 Add sorting functionality
BiroAron/ToDo pull request #7
Opened 2023-08-07 13:53 UTC by BiroAron

2023-08-08 05:53 UTC, kincsokiss requested changes

2023-08-08 05:53 UTC, kincsokiss commented on src/components/header/ArrowButton.vue
> +//import UpArrowIcon from '../icons/UpArrowIcon.vue'
Please remove the unused import.

2023-08-08 05:53 UTC, kincsokiss commented on src/components/header/Filter.vue
> +      <ArrowButton class=""></ArrowButton>
Please remove the empty class attribute.

2023-08-08 05:53 UTC, kincsokiss commented on src/components/todo/ToDoList.vue
>        <Searchbar class="mb-15" @set-search-query="setSearcQuery" />
There is a misspelling issue in `setSearcQuery`. It has to be `setSearchQuery`.

2023-08-08 14:04 UTC, gerebdavid commented on src/components/header/ArrowButton.vue
> +    :class="setBgColor"
This should be getBgColor

2023-08-08 14:04 UTC, gerebdavid commented on src/components/header/ArrowButton.vue
> +    <DownArrowIcon v-if="sortAscending"></DownArrowIcon>
Use v-if v-else

2023-08-08 14:04 UTC, gerebdavid commented on src/components/header/Filter.vue
> +const activeortButtonColor = computed(() =>
There is a typo

2023-08-08 14:05 UTC, gerebdavid commented on src/components/header/Filter.vue
> +<script setup lang="ts">
Please follow the style guide, and move computeds before functions

2023-08-08 14:07 UTC, gerebdavid commented on src/components/todo/ToDoList.vue
> +  } else {
dont need else if you return inside if

2023-08-08 14:07 UTC, gerebdavid commented on src/components/todo/ToDoList.vue
> +  } else {
same

2023-08-09 07:02 UTC, kincsokiss approved these changes

2023-08-09 07:12 UTC, tamasm-wg approved these changes

2023-08-10 10:44 UTC, merged